<?php if($this->success): ?>


<div id="newUserFormHeader">
	<h1>Sie haben sich erfolgreich im Systhem registriert!</h1>
	<h2>Sie können sich sofort mit Ihren Zugangsdaten anmleden und unser Angebot in vollem Umfang nutzen...</h2>
</div>


<?php else: ?>


<script type="text/javascript">
<!--
$(document).ready( function(){
	$('#createUserForm').ajaxForm({
		target: '#createUserFormWrapper'
	});
	$("#picker3").birthdaypicker({
		dateFormat: "bigEndian",
		monthFormat: "long",
		placeholder: false,
		hiddenDate: false
	});
});
//-->
</script>

<div id="newUserFormHeader">
	<h1>Jetzt Anmelden</h1>
	<h2>Einfach das Formular ausfüllen und Ihre Lebensgeschichte beginnt</h2>

	<div id="contactform">
		<form id="createUserForm" action="/index/create-user-form"
			method="post">
			<input type="hidden" name="formType" value="createUserForm" />
			<div>
				<label for="inputUsername"><?php echo $this->usernameHeadline ?> </label>
				<input id="inputUsername" class="inputfeld" name="inputUsername"
					value="<?php echo $this->inputUsername ?>" type="text" size="40"
					maxlength="30" />
			</div>
			<div>
				<label for="inputEMail"><?php echo $this->eMailHeadline ?> </label>
				<input id="inputEMail" class="inputfeld" name="inputEMail"
					type="text" value="<?php echo $this->inputEMail ?>" size="40"
					maxlength="40" />
			</div>
			<div>
				<label for="inputEMail2"><?php echo $this->eMail2Headline ?> </label>
				<input id="inputEMail2" class="inputfeld" name="inputEMail2"
					value="<?php echo $this->inputEMail2 ?>" type="text" size="40"
					maxlength="40" />
			</div>
			<div>
				<label for="inputPassword"><?php echo $this->passwordHeadline ?> </label>
				<input id="inputPassword" class="inputfeld" name="inputPassword"
					type="password" size="40" maxlength="40" />
			</div>
			<div class="picker" id="picker3"></div>
			<input type="submit" class="button" value="REGISTRIEREN" />
		</form>
	</div>
</div>


<?php endif;