<script type="text/javascript">

<!--
var test = "test";

$(document).ready(function() { 
	$("#loginFormWrapper").load("/index/login-form");
    $("#createUserFormWrapper").load("/index/create-user-form");
});

//-->
</script>
<div id="wrap">
        <div id="header">
        	<div class="page">
                <div class="logo"><a href="/index"><img src="/images/logitLogo.png" width="216" height="60" alt="Logit.net - Die Lifelogging Community" /></a></div>
                    <div id="loginFormWrapper">
                    	<!-- content should be replaced by ajax! -->
                    </div>
              		<div class="clear"></div>
              </div>

        </div>
        <div id="main" class="clearfix">
            <div id="content">
			<div id="createUserFormWrapper">
				<!-- content should be replaced by ajax! -->
			</div>
			<div class="startBild">
                	<img src="/images/logit_community.png" width="635" height="349" alt="Logit.net - Die Lifelogging-Community" />
                </div><!--startbild-->

             </div>
        </div>
    </div>
        <div id="footer">
            <div class="page">
                <div class="footercolumn">
                    <h1>FEATURES</h1>
                    <p>Bildaufnahme mit Ihrem Smartphone</p>
                    <p>Intelligenter Such-Algorithmus</p>
                    <p>Gezielte Suche</p>
                    <p>weitere Features von logIt.net</p>
                </div>
                <div class="footercolumn">
                    <h1>FAQ</h1>
                    <p>Hier finden Sie Antworten auf Ihre Fragen  zu der Funktionsweise
                    von LogIt.net und nützliche Tipps, die Ihnen den Einstieg erleichtern.</p>

                    <p>FAQ`s aufrufen</p>
                </div>
                <div class="footercolumn">
                    <h1>ABOUT</h1>
                    <p>LogIt.net ist ein Projekt der Fachhochschule Furtwangen, das sich mit dem Thema Lifelogging auseinandersetzt.
                    Erfahren Sie mehr über logIt.net</p>
                </div>
            </div>

        </div>
