
<form class="standardForm" method="post" action="/view/create-user">
	<label>inputFirstName</label>
	<?php echo $this->inputFirstName; ?>
	<br>
	
	<label>inputLastName</label>
	<?php echo $this->inputLastName; ?>
	<br>
	
	<label>inputUserName</label>
	<?php echo $this->inputUserName; ?>
	<br>
	
	<label>inputPassword</label>
	<?php echo $this->inputPassword; ?>
	<br>

	<label>inputSubmit</label>
	<?php echo $this->inputSubmit; ?>
	<br>
	
</form>