<div id="header">
	<div class="page">
    	<div class="logo"><img src="/images/logo.png" width="216" height="60" alt="logo" /></div><!--logo-->
        <div class="headlogin">
          <table width="400" border="0">
            <tr>
              <td><p>E-Mail:</p></td>
              <td><p>Passwort:</p></td>
              <td>&nbsp;</td>
            </tr>
            <tr>
              <td><input class="inputfeld" name=benutzername size=20></td>
              <td><input class="inputfeld" name=passwort size=20></td>
              <td><input type=submit class="login" value=""></td>
            </tr>
            <tr>
              <td><img src="/images/facebookbutton.jpg" width="100" height="14" alt="facebooklogin" /></td>
              <td><p class="vergessen">Passwort vergessen?</p></td>
              <td>&nbsp;</td>
            </tr>
          </table>
        </div><!--login-->
    </div><!--page header-->
</div><!--header-->
<div class="main start">
	<div id="startlogin">
    	<div id="loginform">
        	<div id="contactheader">
            	<h2>Jetzt Anmelden</h2>
                <p>&nbsp;</p>
                <h3>Einfach das Formular ausfüllen und Ihre Lebensgeschichte beginnt</h3>
                <p>&nbsp;</p>
            </div><!--überschrift kontaktformular-->
        	<div id="contactform">
            	<input type=hidden name="pflicht" value="Benutzername,E-Mail,Passwort">
<table>
	<td align=left><p>Benutzername:</p></td>
	<tr>
	<td><input class="inputfeld" name=benutzername size=40></td>
	<tr>
	<td align=left><p>Ihre E-Mail:</p></td>
	<tr>
	<td><input class="inputfeld" name=email size=40></td>
	<tr>
	<td align=left><p>Ihre E-Mail bestätigen:</p></td>
	<tr>
	<td><input class="inputfeld" name=emailbest size=40></td>
	<tr>
	<td align=left><p>Passwort:</p></td>
	<tr>
	<td><input class="inputfeld" name=passwort size=40></td>
	<tr>
	<td align=left><p>Geburtstag:</p></td>
	<tr>
	<td>
		<select class="inputfeld" name=Tag size=1>
			<option>1
			<option>2
			<option>3
			<option>4
			<option>5
			<option>6
			<option>7
			<option>8
			<option>9
            <option>10
			<option>11
			<option>12
			<option>13
			<option>14
			<option>15
			<option>16
			<option>17
			<option>18
			<option>19
			<option>20
			<option>21
			<option>22
			<option>23
			<option>24
            <option>25
			<option>26
			<option>27
			<option>28
			<option>29
			<option>30
            <option>31		
        </select>
		<select class="inputfeld" name=Monat size=1>
			<option>Januar
			<option>Februar
			<option>März
			<option>April
			<option>Mai
			<option>Juni
			<option>Juli
			<option>August
			<option>September
            <option>Oktober
			<option>November
			<option>Dezember
		</select>
		<select class="inputfeld" name=Jahr size=1>
			<option>1971
			<option>1972
			<option>1973
			<option>1974
			<option>1975
			<option>1976
			<option>1977
			<option>1978
			<option>1979
			<option>1980
			<option>1981
			<option>1982
			<option>1983
			<option>1984
			<option>1985
			<option>1986
			<option>1987
			<option>1988
			<option>1989
            <option>1990
			<option>1991
			<option>1992
			<option>1993
		</select>
	</td>
	<tr>
	<td colspan=2 align=left>
		<input type=submit class="button" value="Registrieren">
	</td>
</table>
            </div><!--kontaktformular-->
        </div><!--loginform-->
        <div id="startbild"><img src="/images/startbild.jpg" width="635" height="349" alt="intro" /></div><!--startbild-->
    </div><!--start login-->
</div><!--main-->
<div id="footer">
	<div class="page">
    	<div class="footercolumn">
        	<h2>FEATURES</h2>
            <p>Bildaufnahme mit Ihrem Smartphone</p>
            <p>Intelligenter Such-Algorithmus</p>
            <p>Gezielte Suche</p>
            <p>weitere Features von logIt.net</p>
			
        </div><!--footercolumn faq-->
    	<div class="footercolumn">
        	<h2>FAQ</h2>
            <p>Hier finden Sie Antworten auf Ihre Fragen  zu der Funktionsweise
			von LogIt.net und nützliche Tipps, die Ihnen den Einstieg erleichtern.</p>
			<p>FAQ`s aufrufen</p>
        </div><!--footercolumn-->
    	<div class="footercolumn">
        	<h2>ABOUT</h2>
            <p>LogIt.net ist ein Projekt der Fachhochschule Furtwangen, das sich mit dem Thema Lifelogging auseinandersetzt.
            Erfahren Sie mehr über logIt.net</p>
        </div><!--footercolumn-->
    </div><!--page footer-->
</div><!--footer-->