<script type="text/javascript">
<!--
$('#createUserForm').ajaxForm({
	target: '#createNewUserForm'
});
//-->
</script>

<!-- comment zum Testen von Git und Github Forkeing und Pulling usw //-->

<div id="contactform">
<form id="createUserForm" action="/ajax/create-user-form">
<input type="hidden" name="formType" value="createUserForm">
<table>
	<td align=left><p><?php echo $this->usernameHeadline ?></p></td>
	<tr>
	<td><input class="inputfeld" name="inputUsername" size=40></td>
	<tr>
	<td align=left><p><?php echo $this->eMailHeadline ?></p></td>
	<tr>
	<td><input class="inputfeld" name="inputEMail" size=40></td>
	<tr>
	<td align=left><p><?php echo $this->eMail2Headline ?></p></td>
	<tr>
	<td><input class="inputfeld" name="inputEMail2" size=40></td>
	<tr>
	<td align=left><p><?php echo $this->passwordHeadline ?></p></td>
	<tr>
	<td><input class="inputfeld" name="inputPassword" size=40></td>
	<tr>
	<td align=left><p>Geburtstag:</p></td>
	<tr>
	<td>
		<select class="inputfeld" name=Tag size=1>
			<option>1
			<option>2
			<option>3
			<option>4
			<option>5
			<option>6
			<option>7
			<option>8
			<option>9
            <option>10
			<option>11
			<option>12
			<option>13
			<option>14
			<option>15
			<option>16
			<option>17
			<option>18
			<option>19
			<option>20
			<option>21
			<option>22
			<option>23
			<option>24
            <option>25
			<option>26
			<option>27
			<option>28
			<option>29
			<option>30
            <option>31		
        </select>
		<select class="inputfeld" name=Monat size=1>
			<option>Januar
			<option>Februar
			<option>März
			<option>April
			<option>Mai
			<option>Juni
			<option>Juli
			<option>August
			<option>September
            <option>Oktober
			<option>November
			<option>Dezember
		</select>
		<select class="inputfeld" name=Jahr size=1>
			<option>1971
			<option>1972
			<option>1973
			<option>1974
			<option>1975
			<option>1976
			<option>1977
			<option>1978
			<option>1979
			<option>1980
			<option>1981
			<option>1982
			<option>1983
			<option>1984
			<option>1985
			<option>1986
			<option>1987
			<option>1988
			<option>1989
            <option>1990
			<option>1991
			<option>1992
			<option>1993
		</select>
	</td>
	<tr>
	<td colspan=2 align=left>
		<input type=submit class="button" value="Registrieren">
	</td>
</table>
</form>
</div><!--kontaktformular-->