<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>logit.net</title>
<link href="/css/map.css" rel="stylesheet" type="text/css">
<link href="/css/style.css" rel="stylesheet" type="text/css" />
<link href="/css/form.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/js/jQuery_dev.js"></script>
<script type="text/javascript" src="/js/jquery.form.js"></script>
<script type="text/javascript" src="/js/bday-picker.min.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript" src="/daten/data.json"></script>
<script type="text/javascript" src="/js/map/markerclusterer_packed.js"></script>
<script type="text/javascript" src="/js/map/map.js"></script>
<!--[if !IE 7]>
	  <style type="text/css">
	      #wrap {display:table;height:100%}
	  </style>
	<![endif]-->
</head>

<body>
<?php
$auth = Zend_Auth::getInstance();

if($auth->hasIdentity()){?>
	<div id="wrap">
		<div id="header">
			<div class="page">
				<div class="logo">
					<img src="images/logitLogo.png" width="216" height="60" alt="logo" />
				</div>
				<div class="headlogin">
					<div class="profil">
						<img src="/images/profilButton.gif" width="159" height="42"
							alt="Profil" />
							
					</div>
				</div>
				<div class="clear"></div>
				<div id="naviButtons">
					<img src="/images/ansichtButton.gif" width="93" height="34"
						alt="Ansicht" /> <img src="/images/filterButton.gif" width="93"
						height="34" alt="Filter" /> <img
						src="/images/logsAbspielenButton.gif" width="124" height="34"
						alt="Abspielen" />
					<div class="uploadLogs">
						<img src="/images/uploadLogs.gif" width="113" height="33"
							alt="Logs uploaden" />
					</div>
				</div>


			</div>
		</div>
		<div id="main">
		
		
		<?php echo $this->layout()->content;  ?>
		
		
			<!--  <div id="content"> -->
				<?php //echo $this->layout()->content;  ?>
			<!-- </div> -->
		</div>
	</div>
	<div id="footer">

		<div class="page">
			<div class="footercolumn">
				<h1>FEATURES</h1>
				<p>Bildaufnahme mit Ihrem Smartphone</p>
				<p>Intelligenter Such-Algorithmus</p>
				<p>Gezielte Suche</p>
				<p>weitere Features von logIt.net</p>

			</div>
			<div class="footercolumn">
				<h1>FAQ</h1>
				<p>Hier finden Sie Antworten auf Ihre Fragen zu der Funktionsweise
					von LogIt.net und nützliche Tipps, die Ihnen den Einstieg
					erleichtern.</p>
				<p>FAQ`s aufrufen</p>
			</div>
			<div class="footercolumn">

				<h1>ABOUT</h1>
				<p>LogIt.net ist ein Projekt der Fachhochschule Furtwangen, das sich
					mit dem Thema Lifelogging auseinandersetzt. Erfahren Sie mehr über
					logIt.net</p>
			</div>
		</div>
	</div>
	<?php
}else{
	echo $this->layout()->content;
}

?>
</body>
</html>
