[{
	"id": "idahoTimeline",
    "focus_date": "<?php echo $this->obUser->getLastLog()->getDateShot(); ?>",
    "initial_zoom": "47",
	"color": "#82530d",
	"size_importance": "false",
    "events":
    [
<?php 
foreach ($this->arrLogs as $key=>$log) {
	?> 
	{		"id": "<?php echo $log->getId();?>",
			"title": " ",
			"startdate": "<?php echo $log->getDateShot();?>",
			"date_limit": "ye",
			"description": "hier kann auch HTML stehen vllt das bild in groß?",
	        "low_threshold": "0",
	        "high_threshold": "60",
	        "importance": "<?php echo $key ?>",
			"image": "daten/pics/45/<?php echo $log->getPicIdent(); ?>",
			"image_class": "layout",
			"ypix": "500",
			"slug": "" <?php 
			if ($key != count($this->arrLogs)-1) {
				echo '},';
			}else{
				echo '}';
			};
	}
?>
]
}]

