
	
<div id="main">
	<div id="addFriends" style="z-index: 1000; position: absolute; margin: 20px;">
		<div id="addFriendsTextfield" title="Finde Freunde und füge Sie zu Deiner Timeline hinzu">
			<input type="text" value="Freunde hinzufügen" id="addFriendsTextfieldId" name="addFriendsTextfield" />
		</div>
		<div id ="friendSearchList">
		</div>
		
	</div>
	<div id="legende" style="z-index: 2; position: absolute; margin-left: 20px; margin-top: 50px;"></div>
	<div id='placement'></div>
	
	
	<!-- 3rd party libs -->
	
	<script src="/js/timeglider/underscore-min.js" type="text/javascript" charset="utf-8"></script>
	
	<script src="/js/timeglider/backbone-min.js" type="text/javascript" charset="utf-8"></script>
	
	
	<script src="/js/timeglider/jquery.tmpl.js" type="text/javascript" charset="utf-8"></script>

	<script src="/js/timeglider/ba-debug.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="/js/timeglider/ba-tinyPubSub.js" type="text/javascript" charset="utf-8"></script>
	
	<script src="/js/timeglider/jquery.mousewheel.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="/js/timeglider/jquery.ui.ipad.js" type="text/javascript" charset="utf-8"></script>
	<script src="/js/timeglider/raphael-min.js" type="text/javascript" charset="utf-8"></script>
	
	<script src="/js/timeglider/jquery.global.js" type="text/javascript" charset="utf-8"></script>	

	<!-- TIMEGLIDER -->
	<script src="/js/timeglider/timeglider/TG_Date.js" type="text/javascript" charset="utf-8"></script>
    <script src="/js/timeglider/timeglider/TG_Org.js" type="text/javascript" charset="utf-8"></script>
    
	<script src="/js/timeglider/timeglider/TG_Timeline.js" type="text/javascript" charset="utf-8"></script> 
	<script src="/js/timeglider/timeglider/TG_TimelineView.js" type="text/javascript" charset="utf-8"></script>
	<script src="/js/timeglider/timeglider/TG_Mediator.js" type="text/javascript" charset="utf-8"></script> 
	<script src="/js/timeglider/timeglider/timeglider.timeline.widget.js" type="text/javascript" charset="utf-8"></script>
	
	

</div>


	
