

<div id="main">
	<div id='placement'></div>
	
	
	<!-- 3rd party libs -->
	
	<script src="/js/timeglider/underscore-min.js" type="text/javascript" charset="utf-8"></script>
	
	<script src="/js/timeglider/backbone-min.js" type="text/javascript" charset="utf-8"></script>
	
	
	<script src="/js/timeglider/jquery.tmpl.js" type="text/javascript" charset="utf-8"></script>

	<script src="/js/timeglider/ba-debug.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="/js/timeglider/ba-tinyPubSub.js" type="text/javascript" charset="utf-8"></script>
	
	<script src="/js/timeglider/jquery.mousewheel.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="/js/timeglider/jquery.ui.ipad.js" type="text/javascript" charset="utf-8"></script>
	<script src="/js/timeglider/raphael-min.js" type="text/javascript" charset="utf-8"></script>
	
	<script src="/js/timeglider/jquery.global.js" type="text/javascript" charset="utf-8"></script>	

	<!-- TIMEGLIDER -->
	<script src="/js/timeglider/timeglider/TG_Date.js" type="text/javascript" charset="utf-8"></script>
    <script src="/js/timeglider/timeglider/TG_Org.js" type="text/javascript" charset="utf-8"></script>
    
	<script src="/js/timeglider/timeglider/TG_Timeline.js" type="text/javascript" charset="utf-8"></script> 
	<script src="/js/timeglider/timeglider/TG_TimelineView.js" type="text/javascript" charset="utf-8"></script>
	<script src="/js/timeglider/timeglider/TG_Mediator.js" type="text/javascript" charset="utf-8"></script> 
	<script src="/js/timeglider/timeglider/timeglider.timeline.widget.js" type="text/javascript" charset="utf-8"></script>
	
	

  <script type='text/javascript'>

	$(function () { 
		
		var tg1 = $("#placement").timeline({
				"min_zoom":5, 
				"max_zoom":100, 
				"show_centerline":true,
				"data_source":"json_tests/idaho.json",
				"show_footer":false,
				"display_zoom_level":true,
				"event_overflow":"scroll"
		});
		
		
		$("#scrolldown").bind("click", function() {
			$(".timeglider-timeline-event").animate({top:"+=100"})
		})
		
		$("#scrollup").bind("click", function() {
			$(".timeglider-timeline-event").animate({top:"-=100"})
		})
		
    }); // end document-ready
	
</script>

</div>


	
