<meta charset="utf-8">
	
	<style>
	.ui-autocomplete-loading { background: white url('images/ui-anim_basic_16x16.gif') right center no-repeat; }
	</style>
	<script>
	$(function() {
		var cache = {},
			lastXhr;
		$( "#user" ).autocomplete({
			minLength: 2,
			source: function( request, response ) {
				var term = request.term;
				if ( term in cache ) {
					response( cache[ term ] );
					return;
				}

				lastXhr = $.getJSON( "/User/autocomplete-user", request, function( data, status, xhr ) {
					cache[ term ] = data;
					if ( xhr === lastXhr ) {
						response( data );
					}
				});
			}
		});
	});
	$(function() {
		var cache = {},
			lastXhr;
		$( "#friends" ).autocomplete({
			minLength: 2,
			source: function( request, response ) {
				var term = request.term;
				if ( term in cache ) {
					response( cache[ term ] );
					return;
				}

				lastXhr = $.getJSON( "/User/autocomplete-friends", request, function( data, status, xhr ) {
					cache[ term ] = data;
					if ( xhr === lastXhr ) {
						response( data );
					}
				});
			}
		});
	});
	</script>



<div class="demo">

<div class="ui-widget">
	<label for="friends">Friends: </label>
	<input id="friends" />
</div>

<div class="ui-widget">
	<label for="user">User: </label>
	<input id="user" />
</div>

</div><!-- End demo -->