<?php 
// <!-- Anpassen der Mapgrš§e - ... css/map.css  -->
// <!-- Einstellungen unter - js/map/map.js  -->
// <!-- Cluster Javascript - js/map/cluster....  -->
// <!-- Koordinaten + Bilder - daten/data.json  -->
?>

<script type="text/javascript">
	$(document).ready(function() { 
		initialize(); 
	});
</script>
	<input type="checkbox" name="PopUp" id="PopUp">PopUp	
  	<div id="map"></div>
  	<div id="clusterPopUp" onmouseup=clusterDivInvisible();>
    	Hallo
  </div>
  
  

